pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/shahraza0098/milestone_practice.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('practice_project2') {
                    bat 'mvn clean test'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}